-- MySQL Script generated by MySQL Workbench
-- Sat Jan 15 21:09:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Uzytkownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uzytkownik` (
  `idUzytkownik` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `haslo` VARCHAR(45) NOT NULL,
  `uprawnienia` ENUM('admin', 'uzytkownik') NOT NULL,
  PRIMARY KEY (`idUzytkownik`),
  UNIQUE INDEX `E-mail_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `tytul` VARCHAR(45) NULL,
  `data dodania` DATE NULL,
  `godzina dodania` TIME NULL,
  `Uzytkownik_idUzytkownik` INT NOT NULL,
  PRIMARY KEY (`idPost`, `Uzytkownik_idUzytkownik`),
  INDEX `fk_Post_Uzytkownik1_idx` (`Uzytkownik_idUzytkownik` ASC) ,
  CONSTRAINT `fk_Post_Uzytkownik1`
    FOREIGN KEY (`Uzytkownik_idUzytkownik`)
    REFERENCES `mydb`.`Uzytkownik` (`idUzytkownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wiadomosc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wiadomosc` (
  `idWiadomosc` INT NOT NULL AUTO_INCREMENT,
  `tytul` VARCHAR(45) NULL,
  `wiadomosc` VARCHAR(225) NULL,
  `Uzytkownik_idUzytkownik` INT NOT NULL,
  PRIMARY KEY (`idWiadomosc`, `Uzytkownik_idUzytkownik`),
  INDEX `fk_Wiadomosc_Uzytkownik1_idx` (`Uzytkownik_idUzytkownik` ASC) ,
  CONSTRAINT `fk_Wiadomosc_Uzytkownik1`
    FOREIGN KEY (`Uzytkownik_idUzytkownik`)
    REFERENCES `mydb`.`Uzytkownik` (`idUzytkownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Odbiorca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Odbiorca` (
  `idOdbiorca` INT NULL AUTO_INCREMENT,
  `Wiadomosc_idWiadomosc` INT NOT NULL,
  PRIMARY KEY (`idOdbiorca`, `Wiadomosc_idWiadomosc`),
  INDEX `fk_Odbiorca_Wiadomosc_idx` (`Wiadomosc_idWiadomosc` ASC) ,
  CONSTRAINT `fk_Odbiorca_Wiadomosc`
    FOREIGN KEY (`Wiadomosc_idWiadomosc`)
    REFERENCES `mydb`.`Wiadomosc` (`idWiadomosc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KATEGORIA` (
  `idKATEGORIA` INT NOT NULL AUTO_INCREMENT,
  `tresc posta` VARCHAR(300) NULL,
  `Post_idPost` INT NOT NULL,
  `Post_Uzytkownik_idUzytkownik` INT NOT NULL,
  PRIMARY KEY (`idKATEGORIA`, `Post_idPost`, `Post_Uzytkownik_idUzytkownik`),
  INDEX `fk_KATEGORIA_Post1_idx` (`Post_idPost` ASC, `Post_Uzytkownik_idUzytkownik` ASC) ,
  CONSTRAINT `fk_KATEGORIA_Post1`
    FOREIGN KEY (`Post_idPost` , `Post_Uzytkownik_idUzytkownik`)
    REFERENCES `mydb`.`Post` (`idPost` , `Uzytkownik_idUzytkownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
